# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: check-added-large-files
    - id: check-ast
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.3.0
  hooks:
    - id: reorder-python-imports
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5.3
  hooks:
    - id: autopep8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.770
  hooks:
    - id: mypy
